#!/usr/bin/env python3
"""Exports the executed notebook/part5_queue.ipynb to Markdown (no `jupyter nbconvert` needed).

    python3 notebook/run_notebook.py && python3 notebook/export_markdown.py

Writes notebook/part5_queue.md and the figures of the outputs to notebook/part5_queue_files/. The Markdown has the text,
the code, the printed results and the figures of the last execution, so the Part 5 answers can be read (or presented)
without a server, a Prometheus or Jupyter.
"""
import base64
import os
import shutil

import nbformat

SRC = "notebook/part5_queue.ipynb"
OUT = "notebook/part5_queue.md"
FIGS = "notebook/part5_queue_files"

nb = nbformat.read(SRC, as_version=4)
shutil.rmtree(FIGS, ignore_errors=True)
os.makedirs(FIGS)
parts = [
    "<!-- Generated by notebook/export_markdown.py from notebook/part5_queue.ipynb (last execution). Do not edit by hand. -->\n"
]
fence = lambda text, lang="text": f"```{lang}\n{text.rstrip()}\n```\n"
n_fig = 0
for i, cell in enumerate(nb.cells):
    src = cell.source
    if cell.cell_type == "markdown":
        parts.append(src + "\n")
        continue
    parts.append(fence(src, "python"))
    for out in cell.get("outputs", []):
        kind = out.output_type
        if kind == "stream":
            parts.append("Output:\n\n" + fence(out.text))
        elif kind in ("execute_result", "display_data"):
            data = out.data
            if "image/png" in data:
                n_fig += 1
                name = f"cell{i:02d}_fig{n_fig}.png"
                with open(os.path.join(FIGS, name), "wb") as f:
                    f.write(base64.b64decode(data["image/png"]))
                parts.append(f"![figure {n_fig}](part5_queue_files/{name})\n")
            elif "text/plain" in data:
                parts.append("Result:\n\n" + fence(data["text/plain"]))
        elif kind == "error":
            parts.append("Error:\n\n" + fence("\n".join(out.traceback)))
with open(OUT, "w") as f:
    f.write("\n".join(parts))
print(f"wrote {OUT} ({len(nb.cells)} cells, {n_fig} figures in {FIGS}/)")
