apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
  namespace: gpu-serving
type: Opaque
stringData:
  LITELLM_MASTER_KEY: "${LITELLM_MASTER_KEY}"
  SUPERLINKED_API_KEY: "${SUPERLINKED_API_KEY}"
# This will require a .env and then a envsubst < cluster/litellm/secret.yaml | kubectl apply -f -
